Fix Inertia Default Banner Component Does Not Show After Dismissing
laravel/jetstream pull request #826
Opened 2021-07-13 06:59 UTC by jamesbhatta

Right now dismissing the banner, it is not shown when newer message is flashed because the show property is set to false while dismissing.

This PR removes the show property and instead only depend upon the message property to toggle the banner. While dismissing just set ``this.$page.props.jetstream.flash.banner == null``

2021-07-13 09:23 UTC, claudiodekker requested changes
Could we instead use a watcher (or some other approach) that updates the `show` property? 

Right now, this PR is modifying props (albeit deeply nested), which isn't recommended in Vue.

2021-07-13 12:13 UTC, taylorotwell commented
Feel free to adjust the behavior of the banner in your own applications.

2021-07-13 12:13 UTC, closed without merging

2021-07-13 12:59 UTC, jamesbhatta commented
For most of us, I think we expect to dismiss only the current banner notification not to disable all of the upcoming ones.

2022-03-22 19:11 UTC, eskiesirius commented
any fix on this issue?

2022-03-24 08:27 UTC, jamesbhatta commented
You can check the changes in commit and customize as you need.